---
version: "1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /Users/user/Desktop/Projects/composeplex/library:/config
      - /Users/user/Desktop/Projects/composeplex/tvseries:/tv
      - /Users/user/Desktop/Projects/composeplex/movies:/movies
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989" # Expose Sonarr on port 8989
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/sonarr/config:/config # Replace with your config path
      - /Users/user/Desktop/Projects/plex/docker/sonarr/shows:/tv # Replace with your TV shows path
      - /Users/user/Desktop/Projects/plex/docker/sonarr/downloads:/downloads # Replace with your downloads path
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878" # Expose Radarr on port 7878
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/radar/config:/config # Replace with your config path
      - /Users/user/Desktop/Projects/plex/docker/radar/movies:/movies # Replace with your movies path
      - /Users/user/Desktop/Projects/plex/docker/radar/downloads:/downloads # Replace with your downloads path
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr-books
    ports:
      - "8787:8787" # Expose Readarr for books on port 8787
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/readarr-booksconfig:/config # Config path for books
      - /Users/user/Desktop/Projects/plex/docker/readarr-books/books:/books # Path for books
      - /Users/user/Desktop/Projects/plex/docker/readarr-books/downloads:/downloads # Path for downloads
    restart: unless-stopped
  readarr-audiobooks:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr-audiobooks
    ports:
      - "8788:8787" # Expose Readarr for audiobooks on port 8788
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/readarr-audiobooks/config:/config # Config path for audiobooks
      - /Users/user/Desktop/Projects/plex/docker/readarr-audiobooks/audiobooks:/audiobooks # Path for audiobooks
      - /Users/user/Desktop/Projects/plex/docker/readarr-audiobooks/downloads:/downloads # Path for downloads
    restart: unless-stopped
