---
version: "1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - "32400:32400"
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Denver
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /Users/user/Desktop/Projects/composeplex/library:/config
      - /Users/user/Desktop/Projects/composeplex/tvseries:/tv
      - /Users/user/Desktop/Projects/composeplex/movies:/movies
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Denver
    ports:
      - "8989:8989" # Expose Sonarr on port 8989
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/sonarr/config:/config # Replace with your config path
      - /Users/user/Desktop/Projects/plex/docker/sonarr/shows:/tv # Replace with your TV shows path
      - /Users/user/Desktop/Projects/plex/docker/sonarr/downloads:/downloads # Replace with your downloads path
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Denver
    ports:
      - "7878:7878" # Expose Radarr on port 7878
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/radar/config:/config # Replace with your config path
      - /Users/user/Desktop/Projects/plex/docker/radar/movies:/movies # Replace with your movies path
      - /Users/user/Desktop/Projects/plex/docker/radar/downloads:/downloads # Replace with your downloads path
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr-books
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Denver
    ports:
      - "8787:8787" # Expose Readarr for books on port 8787
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/readarr-booksconfig:/config # Config path for books
      - /Users/user/Desktop/Projects/plex/docker/readarr-books/books:/books # Path for books
      - /Users/user/Desktop/Projects/plex/docker/readarr-books/downloads:/downloads # Path for downloads
    restart: unless-stopped
  readarr-audiobooks:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr-audiobooks
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Denver
    ports:
      - "8788:8787" # Expose Readarr for audiobooks on port 8788
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/readarr-audiobooks/config:/config # Config path for audiobooks
      - /Users/user/Desktop/Projects/plex/docker/readarr-audiobooks/audiobooks:/audiobooks # Path for audiobooks
      - /Users/user/Desktop/Projects/plex/docker/readarr-audiobooks/downloads:/downloads # Path for downloads
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    ports:
      - "5055:5055" # Expose Overseerr on port 5055
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/overseerr/config:/config # Config path for Overseerr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Denver
    restart: unless-stopped
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Denver
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/tdarr/server:/app/server
      - /Users/user/Desktop/Projects/plex/docker/tdarr/configs:/app/configs
      - /Users/user/Desktop/Projects/plex/docker/tdarr/logs:/app/logs
      - /Users/user/Desktop/Projects/plex/docker/tdarr/media:/media
      - /Users/user/Desktop/Projects/plex/docker/tdarr/transcode_cache:/temp
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=501 # Change to your user ID
      - PGID=20 # Change to your group ID
      - TZ=America/Denver # Change to your timezone
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/sabnzbd/config:/config # Persistent storage for config files
      - /Users/user/Desktop/Projects/plex/docker/sabnzbd/downloads:/downloads # Path for downloads
    ports:
      - 8080:8080 # SABnzbd web interface
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=501 # Change to your user ID
      - PGID=20 # Change to your group ID
      - TZ=America/Denver # Change to your timezone
      - WEBUI_PORT=8081 # Web UI port (can change if needed)
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/qbittorrent/config:/config # Persistent storage for config files
      - /Users/user/Desktop/Projects/plex/docker/qbittorrentd/downloads:/downloads # Path for downloads
    ports:
      - 8081:8081 # qBittorrent Web UI
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Denver
    volumes:
      - /Users/user/Desktop/Projects/plex/docker/bazarr/config:/config
      - /Users/user/Desktop/Projects/plex/docker/bazarr/movies:/movies #optional
      - /Users/user/Desktop/Projects/plex/docker/bazarr/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
