---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /Users/user/Desktop/Projects/composeplex/library:/config
      - /Users/user/Desktop/Projects/composeplex/tvseries:/tv
      - /Users/user/Desktop/Projects/composeplex/movies:/movies
    restart: unless-stopped
